spring:
  application:
    name: kaibank-system
  profiles:
    active: dev
  banner:
    location: classpath:static/banner/banner.txt
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kaibank
    username: kaibankuser
    password: 1qaz2Wsx
    initialization-mode: ALWAYS
    continue-on-error: true
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    default-property-inclusion: non_null
  messages:
    basename: messages/messages
    cache-seconds: -1
    encoding: UTF-8
  devtools:
    restart:
      enabled: true
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api-ui.html
server:
  port: 8081
  servlet:
    contextPath: /kaibank-system
security:
  enable-csrf: false